### ISSUE TITLE
[TASK] Implement Continuous Integration (CI) Process Using GitHub Actions

### ISSUE THREAD

**Issue by NicholasWahome** [harismah/Dwella#19] opened 2024-09-26 05:54 UTC
**Description:** This issue involves setting up a robust Continuous Integration (CI) pipeline for the Dwella project using GitHub Actions. The CI process will streamline development by automating essential tasks, ensuring that every code change is tested, formatted, and analyzed before merging. This will enhance code quality, maintain consistency, and catch potential issues early in the development cycle.

Link to CI: https://github.com/CodePioneerX/Dwella/actions
Related PR to resolve the issue: https://github.com/CodePioneerX/Dwella/pull/48

**Comment by harismah** [comment] 2024-09-29 21:26
Successfully merged and functioning as intended, great work! Closing the issue now!

**Closed as completed by harismah** 2024-09-29 21:26 UTC
Labels: task, CI
